# Generated by Django 5.1.4 on 2025-01-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarcasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produto')),
                ('titulo', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=0)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operacional', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_armazenamento', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_armazenamento', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('memoria_ram_expansivel', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho_tela', models.CharField(blank=True, max_length=50, null=True)),
                ('processador', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidade_processador', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_placa_video', models.CharField(blank=True, max_length=100, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoriasmodel')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.marcasmodel')),
            ],
        ),
    ]
