# Generated by Django 3.2.12 on 2024-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
