# Generated by Django 3.2.12 on 2024-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='imagem',
            field=models.ImageField(default=1, upload_to='produto'),
            preserve_default=False,
        ),
    ]
