# Generated by Django 3.2.12 on 2024-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtomodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
