# Generated by Django 3.2.12 on 2024-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtomodel_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
