# Generated by Django 3.2.12 on 2024-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtomodel_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.categoriasmodel'),
            preserve_default=False,
        ),
    ]
