# Generated by Django 3.2.12 on 2024-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20240509_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='marca',
            field=models.CharField(default='Sem marca', max_length=100),
        ),
    ]
