# Generated by Django 3.2.12 on 2024-05-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produtomodel_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.marcasmodel'),
        ),
    ]
