# Generated by Django 5.0.6 on 2024-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
