# Generated by Django 5.0.6 on 2024-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
